#!/bin/sh
reset_color='\033[0m'
black='\033[0;30m'
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;34m'
purple='\033[0;35m'
cyan='\033[0;36m'
white='\033[0;37m'
darkgray='\033[1;30m'
lightred='\033[1;31m'
lightgreen='\033[1;32m'
lightyellow='\033[1;33m'
lightblue='\033[1;34m'
lightpurple='\033[1;35m'
lightcyan='\033[1;36m'
lightwhite='\033[1;37m'
#
# commit message 체크
regex="update|modify|fix|test|feature|add"
cat .git/COMMIT_EDITMSG | rg -v "^#" | rg -i $regex > /dev/null
ret=$?
if [[ $ret != 0 ]]; then
    printf "${red}check message rule(%s)...\nerror(return:%d)${reset_color}\n" "$regex" "$ret"
    exit 3
fi


