[package]
name = "iterator_custom"
version = "0.1.0"
authors = ["ysoftman <ysoftman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "iterator_custom"
path = "iterator_custom.rs"
