# https://github.com/crate-ci/typos/blob/master/docs/reference.md
[default]
# 오타 대상에서 제외
# valid words
# typos --words
extend-ignore-re = [
    "AttributeID.*Supress.*",
    "speling_module",
    "sed.*",
    "cf-ray.*ICN",
    "CBCEncrypter",
    "iterm2",
    ".mak",
    ".*styl*",
    ".*(?i)ysoftman.*",  # ignorecase https://docs.rs/regex/latest/regex/index.html#grouping-and-flags
]
# valid identifiers(snake_case,CamelCase등으로 구분)
# typos --identifiers
extend-ignore-identifiers-re = [
    "AttributeID.*Supress.*",
    "WSCript",
    "HELO",
    "PN.*",
]

[default.extend-identifiers]
# *sigh* this just isn't worth the cost of fixing
AttributeIDSupressMenu = "AttributeIDSupressMenu"

[default.extend-words]
# Don't correct the surname "Teh"
teh = "teh"

# typos 검사 제외 파일타입
# 지원되는 타입 확인
#typos --type-list
[type.lock]
check-file = false
[type.xml]
check-file = false
[type.jupyter]
check-file = false
[type.asm]
check-file = false
[type.csv]
check-file = false
[type.log]
check-file = false

# 커스텀 파일 타입
[type.raw]
extend-glob=["*.raw"]
check-file = false
[type.mod]
extend-glob=["*.mod"]
check-file = false
[type.ysoftman]
extend-glob=["*.ysoftman"]
check-file = false

# typos 검사 제외파일
[files]
extend-exclude=[
"*.storyboard",
"word2vec.py",
"which.sh",
"TinyXMLTest/*",
"ZlibTest/*",
"data-science-in-python/*",
"Android_ServerMon/*",
"go.sum",
]


# 설치 및 실행
#brew install typos-cli
#typos
