export const GAME_WIDTH = 1280;
export const GAME_HEIGHT = 720;
export const PIXEL = 4;
export const RETRO_FONT = '"Press Start 2P", monospace';
export const GAME_VERSION = "0.1.0";
export const MAX_LEVEL = 30;
export const MAX_HP = 999;
export const MAX_MP = 999;
export const MAX_GOLD = 9999;
