FROM ubuntu:latest
# change root password 
RUN echo "root:docker!" | chpasswd
RUN apt-get update && apt-get install -y locales sudo vim tar git rsync gcc net-tools man python curl wget \
&& rm -rf /var/lib/apt/lists/* \
&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8
RUN groupadd programmer && useradd -m -d /home/ysoftman -g programmer -p ysoftman ysoftman
RUN echo 'ysoftman      ALL=NOPASSWD: ALL, !/sbin/reboot, !/sbin/shutdown, !/sbin/halt, !/usr/bin/poweroff, !/usr/bin/halt' >> /etc/sudoers
USER ysoftman
# 환경설정 저장소 클론 받아 놓기
RUN mkdir -p /home/ysoftman/workspace && cd /home/ysoftman/workspace && git clone https://github.com/ysoftman/myenv
COPY .bashrc /home/ysoftman/.bashrc
COPY .vimrc /home/ysoftman/.vimrc
EXPOSE 80
# 컨테이너 실행시 실행할 명령들
CMD /bin/bash
