/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIManager */

#ifndef _Included_JNIManager
#define _Included_JNIManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIManager
 * Method:    Print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIManager_Print
  (JNIEnv *, jobject);

/*
 * Class:     JNIManager
 * Method:    Add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JNIManager_Add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JNIManager
 * Method:    PrintString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIManager_PrintString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
