// Code generated by protoc-gen-go.
// source: pb_test.proto
// DO NOT EDIT!

/*
Package pb_test is a generated protocol buffer package.

protocol buffer test

It is generated from these files:
	pb_test.proto

It has these top-level messages:
	UserInfo
*/
package pb_test

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type UserInfo struct {
	Aaa              *string `protobuf:"bytes,1,req,name=aaa" json:"aaa,omitempty"`
	Bbb              *int32  `protobuf:"varint,2,opt,name=bbb" json:"bbb,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}

func (m *UserInfo) GetAaa() string {
	if m != nil && m.Aaa != nil {
		return *m.Aaa
	}
	return ""
}

func (m *UserInfo) GetBbb() int32 {
	if m != nil && m.Bbb != nil {
		return *m.Bbb
	}
	return 0
}

func init() {
}
