Name="github_webhook_action"

[server]
Port=80
LogLevel="info"
LogIsJsonFormat=false
WebhookSecretKey="ysoftman"

[action.api]
Enable=false
Mothod="post"
Auth=""
URL="https://httpbin.org/post"
RequestBody="""
{}
"""
