/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_Android_ServerMon_JNIManager */

#ifndef _Included_com_Android_ServerMon_JNIManager
#define _Included_com_Android_ServerMon_JNIManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_Android_ServerMon_JNIManager
 * Method:    Print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_Android_1ServerMon_JNIManager_Print
  (JNIEnv *, jobject);

/*
 * Class:     com_Android_ServerMon_JNIManager
 * Method:    Add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_Android_1ServerMon_JNIManager_Add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_Android_ServerMon_JNIManager
 * Method:    PrintString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_Android_1ServerMon_JNIManager_PrintString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
