- name: hello world by ansible
  # inventory 에 명시된 호스트그룹, inventory 의 모든 호스그룹이라면 all 로 명시
  hosts: testhost1
  # 태스크를 대상 호스트모두에서 동시에 실행하지 않고 대상 호스트를 순차적으로 처리하고 싶은 경우
  # 호스트1에서 끝나면 그다음 호스트2에 대해서 수행 = serial 1
  # 호스트1,2 에서 끝나면 그다음 호스트3,4에 대해서 수행 = serial 2
  serial: 1
  user: ysoftman
  # 대상 서버에서 수행할 작업들 명시
  tasks:
  - name: print hello world
    shell: echo "hello world" > helloworld.txt
    tags: [ helloworld, myname ]
  - name: current path
    shell: pwd > pwd.txt
    tags: mylocation
  - name: who am i
    shell: whoami > whoami.txt
    tags: myname
  - name: clear all files
    shell: rm -fv helloworld.txt pwd.txt whoami.txt
    tags: clearall
  - name: edit file
    # become: yes  # root 권한
    lineinfile:
      # 대상 파일에서
      dest: ./helloworld.txt
      # 해당 스트링이 있는지 체크
      regexp: "^ysoftman edit this file.$"
      # 라인 추가
      line: ysoftman edit this file.
    # edit_file 변수가 yes 인 경우만 실행
    when: edit_file == "yes"
    tags: helloworld
  # 디버깅 출력
  - debug:
      msg: "ansible_distribution: {{ansible_distribution}}  ansible_distribution_major_version: {{ansible_distribution_major_version}}"
    tags:
      - print_debug
