// author : ysoftman
// encoding : utf-8
// title : json 테스트
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
)

const strJson = `
{
"name":"ysoftman", 
"age":20,
"history" : {"date":"20141010", "action":"dosomething"},
"source" : "<script>hello world</script>"
}
`

type JSON_DATA_INNTER struct {
	Date   string
	Action string
}

type JSON_DATA struct {

	//Name	string	// json 키값과 같은 이름의 변수를 선언하던가
	UserName string `json:"name"` // json key tag 를 명시하던가
	Age      int
	History  JSON_DATA_INNTER
	Source   string `json:"source"`
}

// AutoGenerated by https://mholt.github.io/json-to-go/ÎÎ
type JSON_FILE struct {
	Key1 string `json:"key1"`
	Key2 string `json:"key2"`
	Key3 string `json:"key3"`
}

func main() {
	fmt.Println("json test...")

	// bool 형 json 만들기
	json1, _ := json.Marshal(true)
	fmt.Println("json1 = ", string(json1))

	// int 형 json 만들기
	json2, _ := json.Marshal(123)
	fmt.Println("json2 = ", string(json2))

	// string 형 json 만들기
	json3, _ := json.Marshal("ysoftman")
	fmt.Println("json3 = ", string(json3))

	// 배열 json 만들기
	array := []string{"red", "green", "blue"}
	json4, _ := json.Marshal(array)
	fmt.Println("json4 = ", string(json4))

	// 맵 json 만들기
	obj := map[string]string{"name1": "ysoftman", "name2": "hong gil-dong"}
	json5, _ := json.Marshal(obj)
	fmt.Println("json5 = ", string(json5))

	// json 파싱
	json_data := &JSON_DATA{}
	json.Unmarshal([]byte(strJson), &json_data)
	fmt.Println("strJson = ", json_data)
	fmt.Println("strJson = ", json_data.UserName)
	fmt.Println("strJson = ", json_data.Age)
	fmt.Println("strJson = ", json_data.History.Date)
	fmt.Println("strJson = ", json_data.History.Action)

	// HTMLEscape (json 데이터를 HTML <scritp>내에서 사용할때 사용)
	dst := new(bytes.Buffer)
	json.HTMLEscape(dst, []byte(strJson))
	fmt.Println(dst.String())

	// json file 로드
	file, err := ioutil.ReadFile("./json_data.json")
	if err != nil {
		log.Fatal("can't read file ...", err.Error())
	}
	var jsonfile JSON_FILE
	json.Unmarshal(file, &jsonfile)
	fmt.Println(jsonfile)
	fmt.Println(jsonfile.Key1)
	fmt.Println(jsonfile.Key2)
	fmt.Println(jsonfile.Key3)
}
